image: eclipse-temurin:17

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Running build"
    - ./mvnw package

test-job:
  stage: test
  script:
    - echo "Running tests" 