image: eclipse-temurin:17

variables:
   MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - image

build-job:
  stage: build
  script:
    - echo "Running build"
    - ./mvnw package
  artifacts:
    paths:
      - target/*.jar

test-job:
  stage: test
  script:
    - echo "Running tests" 
    - ./mvnw verify

image-job:
  stage: image
  image: docker:20.10.11
  script:
    - docker build -t employees-app:1.0.0 .