image: eclipse-temurin:17

variables:
   MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Running build"
    - ./mvnw package

test-job:
  stage: test
  script:
    - echo "Running tests" 