apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employees-app
  name: employees-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees-app
  template:
    metadata:
      labels:
        app: employees-app
    spec:
      containers:
      - image: employees-app:1.0.1
        name: employees-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employees-app
  name: employees-app
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: employees-app
  type: ClusterIP
